import test from 'node:test';
import assert from 'node:assert/strict';
import {WorkspaceStore} from '../lib/workspace-store.js';
import {compileShot,compactContext} from '../lib/prompt-compiler.js';
import {chatCompletion} from '../lib/chat-stream.js';
test('Windows 临时占用重试、串行保存最新状态且不阻塞事件循环',async()=>{let attempts=0,output,bytes;const store=new WorkspaceStore('fixture',{writeFile:async(_,s)=>{bytes=s;},rename:async()=>{if(attempts++<2)throw Object.assign(Error('locked'),{code:'EPERM'});output=bytes;},unlink:async()=>{}});store.schedule({revision:1});store.schedule({revision:2});let responsive=false;setTimeout(()=>responsive=true,5);await store.flush();assert.equal(responsive,true);assert.equal(JSON.parse(output).revision,2);assert.equal(store.error,'');});
test('磁盘失败保留待保存数据并允许恢复后重试',async()=>{let fail=true,output;const store=new WorkspaceStore('fixture',{writeFile:async(_,s)=>{if(fail)throw Object.assign(Error('full'),{code:'ENOSPC'});output=s;},rename:async()=>{},unlink:async()=>{}});store.schedule({revision:3});await assert.rejects(store.flush(),/ENOSPC/);fail=false;await store.flush();assert.equal(JSON.parse(output).revision,3);});
test('零调用镜头编译仅使用当前镜头与视觉设定，不发送对白和其它章节',()=>{const prompt=compileShot({prompt:'开门',characterIds:['c'],direction:{lighting:'暖光'}},{characters:[{id:'c',name:'林舟',appearance:'绿夹克',notes:'private biography'}],worldbook:[{name:'风格',category:'视觉',content:'胶片'},{name:'历史',category:'历史',content:'long history'}],episodes:[{secret:'other chapter'}]},{title:'店铺 / 夜',dialogue:'long dialogue'});assert.match(prompt,/绿夹克/);assert.match(prompt,/暖光/);assert.doesNotMatch(prompt,/history|dialogue|biography|chapter/);assert.deepEqual(compactContext({dialogue:'',generation:{seed:1},action:'开门'}),{action:'开门'});});
test('流式文本分块返回可见进度并支持取消等待',async()=>{const original=global.fetch;try{const encoder=new TextEncoder();global.fetch=async()=>new Response(new ReadableStream({start(c){c.enqueue(encoder.encode('data: {"choices":[{"delta":{"content":"你好"}}]}\n\n'));c.enqueue(encoder.encode('data: {"choices":[{"delta":{},"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n'));c.close();}}),{headers:{'Content-Type':'text/event-stream'}});const events=[];const data=await chatCompletion({baseUrl:'http://127.0.0.1:1234',keyEnv:'',model:'fixture',maxTokens:128,temperature:0.2},[],new AbortController().signal,e=>events.push(e));assert.equal(data.choices[0].message.content,'你好');assert.ok(events.some(e=>e.characters===2));global.fetch=(_,options)=>new Promise((_,reject)=>options.signal.addEventListener('abort',()=>reject(options.signal.reason),{once:true}));const controller=new AbortController(),pending=chatCompletion({baseUrl:'http://127.0.0.1:1234',keyEnv:''},[],controller.signal);controller.abort();await assert.rejects(pending);}finally{global.fetch=original;}});
