import {readFile} from 'node:fs/promises';
import {Readable} from 'node:stream';
import ffprobe from 'ffprobe-static';
import {run} from './media.js';
import {requireValue,validateEndpoint,validateEnv} from './core.js';
import {request} from './providers.js';
import {secretValue} from './secrets.js';
export const imageDefaults=()=>({provider:'compatible',baseUrl:'https://api.openai.com/v1',model:'gpt-image-1',keyEnv:'IMAGE_API_KEY',size:'1024x1536'});
export function validateImage(c){requireValue(c&&['compatible','automatic1111'].includes(c.provider),'图像服务无效');const u=validateEndpoint(c.baseUrl);validateEnv(c.keyEnv);requireValue(typeof c.model==='string'&&c.model.length<=160,'图像模型 ID 无效');requireValue(['1024x1024','1024x1536','1536x1024'].includes(c.size),'图像尺寸无效');if(c.provider==='automatic1111')requireValue(['localhost','127.0.0.1','[::1]'].includes(u.hostname),'本地 SD 接口仅允许回环地址');return c;}
export async function inspectImage(file,signal){const bytes=await readFile(file);const png=bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),jpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;requireValue(png||jpeg,'参考图仅支持 PNG / JPEG');const result=JSON.parse(await run(process.env.FFPROBE_PATH||ffprobe.path,['-v','error','-protocol_whitelist','file','-format_whitelist','png_pipe,jpeg_pipe','-show_streams','-of','json',file],signal));const v=result.streams?.[0];requireValue(v&&v.width>0&&v.height>0&&v.width*v.height<=40000000,'图片尺寸无效或超过 4000 万像素');return {kind:'image',width:v.width,height:v.height,mime:png?'image/png':'image/jpeg',extension:png?'png':'jpg'};}
export function portraitPrompt(character,mode,instruction,worldbook=[]){requireValue(['portrait','sheet'].includes(mode),'角色图类型无效');requireValue(typeof instruction==='string'&&instruction.length<=5000,'绘图要求过长');return ['角色设计参考图，保持人物外观清晰。',mode==='sheet'?'人物三视图：正面、侧面、背面，同一人物、同一服饰，干净背景，不要文字。':'单人全身立绘，完整展示头部与双脚，干净背景，不要文字。',`人物：${character.name}\n外观：${character.appearance}\n性格：${character.personality}`, ...worldbook.filter(w=>w.category==='视觉').map(w=>w.name+'：'+w.content),instruction].filter(Boolean).join('\n');}
export async function generateImage(c,prompt,signal){validateImage(c);const key=secretValue(c.keyEnv);requireValue(!c.keyEnv||key,'请先配置图像模型密钥');let data;
 if(c.provider==='automatic1111'){const [width,height]=c.size.split('x').map(Number);const r=await request(c.baseUrl,'/sdapi/v1/txt2img',{method:'POST',signal,headers:{'Content-Type':'application/json',...(key?{Authorization:'Bearer '+key}:{})},body:JSON.stringify({prompt,width,height,steps:25,batch_size:1,n_iter:1,...(c.model?{override_settings:{sd_model_checkpoint:c.model},override_settings_restore_afterwards:true}:{})})});data={b64_json:(await r.json()).images?.[0]};}
 else{const r=await request(c.baseUrl,'/images/generations',{method:'POST',signal,headers:{'Content-Type':'application/json',...(key?{Authorization:'Bearer '+key}:{})},body:JSON.stringify({model:c.model,prompt,n:1,size:c.size})});data=(await r.json()).data?.[0];}
 if(data?.b64_json){requireValue(typeof data.b64_json==='string'&&data.b64_json.length<=28*1024*1024,'图片返回内容过大');const encoded=data.b64_json.replace(/^data:image\/(png|jpeg);base64,/,'');requireValue(/^[A-Za-z0-9+/=\r\n]+$/.test(encoded),'图片编码无效');return Readable.from([Buffer.from(encoded,'base64')]);}
 requireValue(data?.url,'图像服务未返回图片');const u=new URL(data.url);requireValue(u.protocol==='https:'&&!u.username&&!u.password,'图像下载地址必须是 HTTPS');const r=await fetch(u,{signal,redirect:'error'});requireValue(r.ok,'图像下载失败');return Readable.fromWeb(r.body);
}
